### ISSUE TITLE
AutoRotate direction argument

### ISSUE THREAD

**Issue by abrightwell** [wando-advanced-robotics/steamworks-robot#8]
Let's add an argument to AutoRate that is the "direction" of the rotation.  This argument should be a set of constants on the class or an Enum. Though, I believe that a constant is simple enough and preferable in this case.

Abstracting this out from a 'sign' on the degrees to turn will help to reduce confusion on current and future programmers as well as observers of our code.

Also, please add documentation in the code that describes what is going on.

Example of what I'd expect to see as an end result would be:

```
// Rotate to the left 60 degrees.
AutoRotate leftCommand = new AutoRotate(60, AutoRotate.LEFT);

// Rotate to the right 60 degrees.
AutoRotate rightCommand = new AutoRotate(60, AutoRotate.RIGHT);
```

**Comment by BearsAreAwsome** [comment]
Fixed in 3d0108d
